# Generated by Django 3.2.12 on 2022-09-12 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=900),
            preserve_default=False,
        ),
    ]
